<!--
.. title: List of Data
-->

Here are links to some datasets potentially of interest to political scientists. However, the data collection process in academia is disaggregated, with many data sets collected by researchers for specific purposes and distributed by the researcher with their paper. 
See also the Washington Library [Data Research Guide](http://guides.lib.uw.edu/c.php?g=341607&p=2299327)

# Repositories

- [Harvard Dataverse](https://dataverse.harvard.edu/) Contains replication data for many political science articles (among other data). The R package [dvn](https://cran.r-project.org/web/packages/dvn/index.html) allows for direct download and upload of data to and from the Dataverse.
- [ICPSR](http://www.icpsr.umich.edu/icpsrweb/landing.jsp) Collection of many political science and economics datasets.

- [Quandl](https://www.quandl.com/) A collection of financial and economic data. The R package [Quandl](https://www.quandl.com/tools/r) allows for easy access to Quandl data within R.
- [General Social Survey(GSS)](http://www3.norc.org/GSS+Website/)

# Economics

- [World Development Indicators (WDI)](http://data.worldbank.org/data-catalog/world-development-indicators). The R package [WDI](https://cran.r-project.org/web/packages/WDI/index.html) allows for downloading data.
- [Penn World Table](http://cid.econ.ucdavis.edu/pwt.html)

# American Politics

- [FRED](https://research.stlouisfed.org/fred2/) Collection of U.S. economic data by the Federal Reserve Bank of St. Louis.
- [data.gov](https://cran.r-project.org/web/views/WebTechnologies.html) U.S. government open data
- [U.S. Census Bureau](http://www.census.gov/) 
- [NOMINATE Ideal Points of U.S. Congress](http://voteview.com/)

# Comparative Politics

- Policy Agendas Project <http://www.policyagendas.org/page/datasets-codebooks>
- Varieties of Democracy (VDEM) project <http://kellogg.nd.edu/projects/vdem/>
- [Polity Project data](http://www.systemicpeace.org/polity/polity4.htm) Political regime characteristics
- [Database of Political Institutions](http://econ.worldbank.org/WBSITE/EXTERNAL/EXTDEC/EXTRESEARCH/0,,contentMDK:20649465~pagePK:64214825~piPK:64214943~theSitePK:469382,00.html)


# International Relations

- Paul Hensel maintains a list of Political Science Datasets <http://www.paulhensel.org/data.html>
- [UCDP/PRIO Armed Conflict](http://www.pcr.uu.se/research/ucdp/datasets/ucdp_prio_armed_conflict_dataset/) Datasets on armed conflict
- [ACLED (Armed Conflict Location and Event Data Project)](http://www.acleddata.com/data/) Real-time data on political violence in African and Asian states
- [OpenEvent Data/Phoenix Data Project](http://openeventdata.org/datasets/OEDA.datasets.php)
- Data version of the CIA World Factbook: <http://jmatchparser.sourceforge.net/factbook/>
- [Paul Hensel&rsquo;s List of International Relations Data](http://www.paulhensel.org/data.html)
- [Issue Correlates of War (ICOW)](http://www.paulhensel.org/icow.html)

# Open Data / Open Government Datasets

- [Sunlight Foundation](http://sunlightfoundation.com/) Provides open data on the U.S. government. Data on Congress, state legislatures, campaign finance, contributions, dockets.
- [ROpenGov](https://ropengov.github.io/) has R packages to access various government related data. For packages to access data on the web from within R see the [Web Technologies and Services](https://cran.r-project.org/web/views/WebTechnologies.html) CRAN Task View.
- [Awesome Public Datasets](https://github.com/caesar0301/awesome-public-datasets) by [caesar0301](https://github.com/caesar0301)
- [Vox](http://www.vox.com/) stories on [github](https://github.com/voxmedia/data-projects)
- NY Times [Upshot](http://www.nytimes.com/upshot/) on [github](https://github.com/TheUpshot)
- Guardian Data Blog [here](http://www.theguardian.com/news/datablog/interactive/2013/jan/14/all-our-datasets-index)
- [Fivethirtyeight](http://fivethirtyeight.com) data on [github](https://github.com/fivethirtyeight/data)
- Catalog of open government data around the world at [DataPortals.org](http://dataportals.org)
- [Sunlight Foundation](http://sunlightfoundation.com/)  Datasets focusing on US government transparency
- [ProPublica](https://www.propublica.org/data/)
- [NYTimes Campaign Finance API](http://developer.nytimes.com/docs/campaign_finance_api/)
- [UCI Machine Learning Repository](http://archive.ics.uci.edu/ml/) : repository of machine learning datasets
- [Open Data on Github](https://github.com/showcases/open-data)

# Cleaning data guide

- [The Quartz guide to bad data](https://github.com/Quartz/bad-data-guide)
