# Research Project Paper Guidelines

The research project paper must comply with the following guidelines.
To help you meet these guidelines start with either this

- Word Document [.docx](pols_503_sp16/files/example-manuscript.docx)
- A [$\mathrm{\LaTeX}$](pols_503_sp16/files/final_project_template.tex) template and R Markdown package for pdf (coming soon ....)

The paper should be submitted as either a Microsoft Word (*.docx*) or PDF file.

The paper must be 15 pages or less, including figures, tables, and references, but not including the title page and abstract. The paper must be formatted in 12 point standard serif font (e.g. Times New Roman), doubled spaced (including footnotes and references), with 1 inch margins. The paper should contain 2--5 figures or tables. The paper should present its content concisely and efficiently with no unnecessary material. In addition to the body text, footnotes and references must be double spaced. New paragraphs should be indicated by indenting the first line; do not add extra spaces between paragraphs. Pages must be numbered, except the title page.

The paper must have a title page with an abstract of 150 words or less. The abstract should provide a concise summary of (1) research topic the paper addresses, (2) the research strategy employed for the analysis, (3) the results obtained from the analysis, and (4) the implications of the findings. The abstract should not contain formal citations to other work.

Sections must not be numbered, instead they should be given short titles. The introduction should not be titled. Authors should only use one level of sections, but authors may use subsections where necessary. Authors should not include paragraph at the end of the introductory section laying out the organization of the paper.

Tables and figures should be inserted into the text of the paper at appropriate locations. Although journal submissions generally discourage use of color, the author is strongly *encouraged* to use appropriate colors in figures. Follow the style guidelines in  Political Analysis guidelines for Tables, Figures, and Numbers and Variables [[URL](http://www.oxfordjournals.org/our_journals/polana/for_authors/general.html)] for presenting quantitative results, and the American Political Science Association's Style Manual for Political Science (revised 2006) [[URL](http://www.apsanet.org/Portals/54/APSA%20Files/publications/APSAStyleManual2006.pdf)] or the [Chicago Manual of Style](http://www.chicagomanualofstyle.org/search.epl) (15th or 16th edition) for all else. These guidelines include text style, citations, appendices, notes, references, and figures/tables.

References should be included at the back of the paper. Citations and references should follow the [APSA](http://www.apsanet.org/Portals/54/APSA%20Files/publications/APSAStyleManual2006.pdf) style.

The paper should be self contained and written for a general political science audience.
While the main text of paper should be a concise summary of results, the author may submit supporting information, in lieu of appendices. This may include descriptions of the data, alternative specifications of statistical methods, and additional tables and figures that elaborate the paper's primary point.

All data and code necessary to reproduce the paper's results **must** be provided.

The use of asterisks or symbols to represent statistical significance is discouraged. Tables should include standard errors rather than $z$-scores, $t$-scores, or $p$-values. Authors reporting that results are "statistically significant" should use the 0.05 level or lower. Results at the 0.10 significance level should not be referred to as "statistically significant". However, the strength of evidence necessary to justify findings cannot be captured by any single criterion, such as the conventional .05 level of statistical significance. The instructor will evaluate the strength of findings on "a range of criteria beyond statistical significance, including substantive significance, theoretical aptness, the importance of the problem under study, and the feasibility of obtaining additional evidence. (APSR)"

These guidelines are derived from those used for submissions by the [American Political Science Review](http://www.apsanet.org/apsrsubmissions), [American Journal of Political Science](http://ajps.org/guidelines-for-manuscripts/), [Journal of Politics](http://www.journals.uchicago.edu/journals/jop/instruct), and [Political Analysis](http://www.oxfordjournals.org/our_journals/polana/for_authors/general.html)
