---
title: Getting Started with Git and GitHub
---

## Git and GitHub

### Install Git

In this course we will use Git, a version control system that allows you to track changes and share your code, and you will submit most of your assignments through GitHub, a website that implements Git and allows you to share code with others. Most software developers use these tools, and a large number of R packages are hosted and can be downloaded from GitHub.

- [Windows](http://git-scm.com/download/win)

    - choose defaults for everything

- [Mac](http://git-scm.com/download/mac)

    - You may get an error message that you cannot install this because it is an unidentified developer.
      Change your settings so you can install it.


### Check that RStudio Knows Git is installed

1. Go to **Global Options > Git SVN**
2. Check that **Git executable** is not empty
3. Click **enable version control interface for RStudio projects** if it is not already checked.

## Create a GitHub account

[Here](https://github.com/join?source=header-home)

    - Choose available Username (keep it professional)
    - Choose the free plan

Now let us know your GitHub account name is. Go [here](https://github.com/UW-POLS503/pols_503_sp16/issues), click on "New Issue", make the title "Add me to the organization", and click on "Sumbit new issue".

## Submitting assignments

### Fork the repository.

For each assignment we will create a new repository in https://github.com/UW-POLS503. First you need to make a copy of that repository to your GitHub account. We call that to create a "fork".

1. Go to https://github.com/UW-POLS503/Assignment_00
2. Click on "Fork". <i class="fa fa-code-fork"></i>
   Now you will see: `https://Github.com/<your_account>/Assignment_00`.

### Clone your new repository

You created a copy of the assignment repository in your GitHub online account. Now you need make a copy of it in your local machine. We call that to "clone" a repository.

1. Open up RStudio
2. Go to `File > New Project > Version Control > Git`
3. Enter the URL of your repository: `https://Github.com/<your_account>/Assignment_00`. If you don't give it a "Project directory name", it will create a directory named "Assignment_00" that will have the original files in the repository plus an `.Rproj` and `.gitingore` file.
4. Select the directory you want to have the repository in. We suggest you create a directory to store all future assignment repositories. Ideally this would be within your directory for the class.

### Edit the README.md file

1. Open the README.md file and edit it: add your name.
2. Save the README.md file.

### Commit and Push your changes (for the first time)

1. Access a terminal from within RStudio: **Tools > Shell...**

2. In the terminal enter the following commands:

```console
git add *
git commit -m 'my first commit'
git push
```
3. `Git` is going to ask for you GitHub account. Type it and Press `enter`.
4. Then it will ask for your GitHub password. Type it. When typing it you are not going to see any number being typed in the terminal but it's actually happening. Press `enter` after typing the password and you should be good to go!
5. Next time you want to commit and push you can do it from within RStudio. You don't need to do it from the console anymore. 

### Commit and Push your changes (after first time)

1. Use the Git pane to commit the changes:
    - Select the files you changed
    - Click on "Commit"
    - Add a commit message and commit

2. Push your changes to the repository

### Pull Request

Now that you pushed your assignment to your online fork of the repository, the last step is to send a `pull request` to add your changes to the main repository.

1. Go to your online version of the repository: `https://Github.com/<your_account>/Assignment_00`
2. Click on "New Pull Request"
3. Click on "Create new pull request"
4. The instructors will be informed that you are done with the assignment.




### Install Github Desktop (optional)

Another graphical interface for Git and GitHub, not directly tied to RStudio, is [GitHub Desktop](https://desktop.github.com/). You may want to install that as an alternative to
working with GitHub through RStudio.


## References

- Rstudio's instructions, [Using Version Control with RStudio](https://support.rstudio.com/hc/en-us/articles/200532077?version=0.99.879&mode=desktop)
- [GitHub training material](https://training.github.com/kit/)
- GitHub's list of [Good Resources for Learning Git and GitHub](https://help.github.com/articles/good-resources-for-learning-git-and-github/)
- Rstudio [Version Control with Rstudio](https://support.rstudio.com/hc/en-us/articles/200532077-Version-Control-with-Git-and-SVN)
- Chapter on [Git and GitHub](http://r-pkgs.had.co.nz/git.html) in Hadley Wickham, *R packages*. Even though the book is about R packages, it is useful.
- [trygit](https://try.github.io/levels/1/challenges/1) is an interactive introduction to git.
- [Software Carpentry](http://swcarpentry.github.io/) has a lesson on [git](http://swcarpentry.github.io/git-novice/).
- Stat 545 [RStudio, Git, GitHub Hell](https://stat545-ubc.github.io/git66_rstudo-git-github-hell.html)
- [Git Cheat Sheet](https://education.github.com/git-cheat-sheet-education.pdf)
- Zach Jones [Git and Github Tutorial](http://zmjones.com/git-github-tutorial/)
- Stack Overflow [Why Should I use version control](http://stackoverflow.com/questions/1408450/why-should-i-use-version-control)
- Stack Overflow [R and version control for the solo data analyst](http://stackoverflow.com/questions/2712421/r-and-version-control-for-the-solo-data-analyst)

Note that although for this course we use git through either the GitHub website or client, or RStudio's interface, git is often used in a shell. If you are unfamiliar with a shell, here are some places to get started:

- [Stat 545](https://stat545-ubc.github.io/git09_shell.html) intro to the shell
- [Terminus](http://web.mit.edu/mprat/Public/web/Terminus/Web/main.html) an interactive way to learn shell
- Philip Guo's [Basic Unix-like command line videos](http://www.ee.surrey.ac.uk/Teaching/Unix/unix1.html)
- <http://www.ee.surrey.ac.uk/Teaching/Unix/unix1.html>
- [userland](https://p1k3.com/userland-book/)
- Software Carpentry lesson [The Unix Shell](http://swcarpentry.github.io/shell-novice/)
- Jeroen Janssens, [Data Science at the Command Line](http://datascienceatthecommandline.com/)

Parts of this module are abstracts from Hadley Wickham’s module on [Git and GitHub](http://r-pkgs.had.co.nz/git.html)
