---
title: "Initial Set Up"
author: "Andreu Casas"
date: "March 28, 2016"
---

## Credit
Parts of this module are abstracts from Hadley Wickham’s module on [Git and GitHub](http://r-pkgs.had.co.nz/git.html)

## Learning Objectives

- You will make sure you have the latest version of R
- You will create a GitHub account
- You will learn how to use Git + GitHub in RStudio

## Latest R version

Some of the packages we will use during this course require the latest R version. So let's now take the moment to be sure that everybody has it. Type `version` in the R console to check what version you have. The latest one is verison 3.2.4 (2016-03-10). If you don't have it, follow the next steps to update it:

- Go to the [R Project](https://cran.fhcrc.org/) website
- Choose the `Download R for` your operation system:
    - Mac: Download `R-3.2.4.pkg`
    - Windows: First click on `base` and then on `Download R 3.2.4 for Windows`
- Restart RStudio

## Git, GitHub, and GitHub Desktop

In this course we will use Git, a version control system that allows you to track changes and share your code, and you will submit most of your assignments through GitHub, a website that implements Git and allows you to share code with others. Most software developers use these tools, and a large number of R packages are hosted and can be downloaded from GitHub. 

- Install Git:
    - [Windows](http://git-scm.com/download/win)
    - [Mac](http://git-scm.com/download/mac)

- Create a GitHub account:
    - [Here](https://github.com/join?source=header-home)

- Install and Set up GitHub Desktop:
    - Download it [here](https://desktop.github.com/) and install it
    - Open GitHub Desktop and set up the inital configuration: GitHub username and Email

## Submitting assignments (1): Fork a repository.

For each assignment we will create a new repository in https://github.com/UW-POLS503. First you need to make a copy of that repository to you GitHub account. We call that to create a "fork". You need to go to the repository and click the `Fork` botton in the header (right-side) of the repository. Let's practice with a sample repository I created: `Assignment 0`: go to https://github.com/UW-POLS503, find the repo, and create a fork.

## Submitting assignments (2): Clone your fork.

In step 1 you created a copy of the assignment repository in you GitHub online account. Now you need make a copy of it in your local machine. We call that to "clone" a repository. I suggest you create first a directory to store all future assignment repositories. Ideally this would be within your directory for the course.

- Go to GitHub Desktop
- Click the plus icon on the right top corner
- Select "Clone"
- Insert the name of the repository to the "Filter" box or scroll down until you find it, and click it

## Submitting assignments (3): Save your assignment in the repository.

Navigate to the repository and create a new directory for your assignment. Use the following naming convention: `acasas-assignment-0` (replace `acasas` with you `netid`). Then:

- Create a new `R Project` in that directory
- Open the new `R Project` and create the assignment (`R Markdown`, `R Script`, etc.)
- Save the assignment

## Submitting assignments (4): Git pane in RStudio.

When opening the `R Project` in the assignment directory, in RStudio you should see the Git pane by the Environment pane. If it's not there:

- In RStudio go to Tools > Global Options
- Select Git/SVN in the left menu
- Click "Enable version control interface for RStudio projects"
- Restart RStudio

Once you have the Git pane in RSutdio and you're done with the assignment:

- `Commit` the assignment:

    - Click the `Commit` botton in the Git pane
    - Select the files you want to `commit` (the assignment files)
    - Add a `commit` message in the top-left box: e.g. `adding acasas assignment0`
    - Click the `Commit` botton under the commit-message box

- `Push` the changes you made in the local version of the repository to the online version

    - Click the green arrow in the Git pane
  
## Submitting assignments (5): Pull request

Now that you pushed your assignment to your online fork of the repository, the last step is to send a `pull request` to add your changes to the main repository. Go to the GitHub site for your online fork (e.g. `https://github.com/<your_github_username>/Assignment0`) and click the green botton "New pull request"





