---
title: "Schedule"
output:
  word_document:
    toc: yes
    toc_depth: '3'
  html_document:
    toc: yes
    toc_depth: 3
---

<style>
h2 {
  font-size: 16px;
  font-weight: bold;
}
h3 {
  font-size: 15px;
  font-weight: bold;
}
h4 {
  font-size: 14px;
  font-weight: bold;
}
</style>


You should expect this schedule to be a dynamic document.
Although the the objectives for this course are fixed, the details of how to accomplish those objectives will depend on the interaction between the instructors and students in the course.

When I make changes, these changes will be recorded in the [history](https://github.com/UW-POLS503/pols_503_sp16/commits/gh-pages/schedule.html) of this page on GitHub so that you can track what has changed.
I will notify you of changes in class or via email.

I will ask the class for feedback frequently---both in class and anonymously via surveys.
Please let me know what is working and what can be improved.
I will make adjustments based on this feedback.


## Week 1

### <time datetime="2016-03-29">Tuesday, March 29</time>

- Introduction
- Install software and set up GitHub accounts

#### Reading

skim after class, I will discuss ideas inspired by these sources:

- Jenny Bryan, Karen Cranston, Justin Kitzez, Lex Nederbragt, Tracy Teal, and Greg Wilson. [Good Enough Practices for Scientific Computing](http://swcarpentry.github.io/good-enough-practices-in-scientific-computing/).
- Matthew Gentzkow and Jesse M. Shapiro. [Code and Data for the Social Sciences: A Practitioner's Guide](http://swcarpentry.github.io/good-enough-practices-in-scientific-computing/). March, 2014. Especially Chapter 3: Version Control. The principles of this are good though I don't follow all their exact prescriptions. The practices adopted for this class are closer to "Good Enough Practices."
- Zachary M. Jones. [Git/Github, Transparency, and Legitimacy in Quantitative Research](http://thepoliticalmethodologist.com/2013/11/18/gitgithub-transparency-and-legitimacy-in-quantitative-research/) *Political Methodologist*
- Carlisle Rainey [Git for Political Science](https://github.com/carlislerainey/git-for-political-science). Combined with Zach Jones' article, provides a discussion on Git and GitHub from a political scientist's point of view.
- Roger Peng. 2011. [Reproducible Research in Computational Science](http://science.sciencemag.org/content/334/6060/1226.full) *Science*
- Roger Peng. [Treading a New Path for Reproducible Research]( http://simplystatistics.org/2013/08/21/treading-a-new-path-for-reproducible-research-part-1/) [The Real Reason Reproducible Research is Important
](http://simplystatistics.org/2014/06/06/the-real-reason-reproducible-research-is-important/).
- Thomas Leeper. 2015. [What's In a Name? The Concepts and Language of Replication and Reproducibility](http://thomasleeper.com/2015/05/open-science-language/). blog post. May 12, 2015.
- Symposium on Openness in Political Science: Data Access and Research Transparency
- Recent [2012 DA-RT Ethics Guide Changes](http://www.dartstatement.org/#!2012-apsa-ethics-guide-changes/c13ay) and the [2014 Journal Editors' Transparency Statement](http://www.dartstatement.org/), and the [Center for Open Science Transparency and Openness Promotion Guidelines](https://cos.io/top/). See the [DA-RT](http://www.dartstatement.org/) website for more information.
-  [APSR Submission Guidelines](http://www.apsanet.org/PUBLICATIONS/Journals/APSR-Submission-Guidelines-2016-in-Brief) section on "Data Access, Production Transparency and Analytic Transparency." and *AJPS* [Guidelines for Preparing Replication Materials](http://media.wix.com/ugd/fa8393_d2b63b1d72ee40599ae27ec28bb3291d.pdf).
- *PS: Political Science and Politics* Symposium on [Openness in Political
Science: Data Access and Research Transparency](http://media.wix.com/ugd/fa8393_d55bef088ac44830bd194b5f80190479.pdf). January 2014.

### <time datetime="2016-03-31">Thursday, March 31</time>

#### Agenda

- Continue set-up of Git and GitHub
- [Getting Started with Git and GitHub](git.html)
- [Assignment 0](https://github.com/UW-POLS503/Assignment_00)


### <time datetime="2016-04-01">Friday, April 1</time>

For loops and functions

- Hadley Wickham [R for Data Science](http://r4ds.had.co.nz/), Chapters [14](http://r4ds.had.co.nz/programming.html), [15](http://r4ds.had.co.nz/pipes.html), [16](http://r4ds.had.co.nz/functions.html), [17](http://r4ds.had.co.nz/data-structures.html), [18](http://r4ds.had.co.nz/iteration.html#for-loops) on For loops.
- Roger Peng. [R Programming for Data Science](https://leanpub.com/rprogramming), Chapter 14: Control Structures, and Chapter 15: Functions.
- Data Camp course [Intermediate R](https://www.datacamp.com/courses/intermediate-r) will help if you need more practice.

R markdown

- [Rstudio Markdown website](http://rmarkdown.rstudio.com/)
- Roger Peng. [Report Writing for Data Science in R](https://leanpub.com/reportwriting) for some more discussion of reproducible research (some of which is more relevant to biostatistics than political science) and discussion of R markdown in particular
- Data Camp course [Reporting with R Markdown](https://www.datacamp.com/courses/reporting-with-r-markdown) for more practice if you need it.



## Week 2

#### Readings

- Chapters 1 and 2 of Wooldridge
- Chapter 1 of *Mostly Harmless Econometrics*
- Review matrix algebra: you should understand what vectors and matrices are. How to add, subtract, and
  multiply them. And what a matrix inverse is, what it's properties are. You don't need to worry about how to calculate a matrix inverse, since you'll never do that by hand.

   - Wooldridge appendix
   - Kahn Academy course [Matrices](https://www.khanacademy.org/math/precalculus/precalc-matrices) lessons:
     Introduction, Representing linear systems of equations, elementary matrix row operations,
     adding and subtracting matrices, multiplying matrices by scalars, properties of matrix addition
     and scalar multiplication, multiplying matrices by matrices, properties of matrix multiplication,
     introduction to matrix inverses.
   - [Matrix algebra handout](files/matrix.pdf)

Friday: paragraph proposal due.

### <time datetime="2016-04-05">Tuesday, April 5</time>

#### Class Agenda

1. Confirm that you can push to GitHub Accounts.
2. Discuss [Project Assignment 1](assignments_project_1.html)
3. Types of research questions, types of analysis. [slides](slides/research_questions_and_design.pdf)

#### Supplementary Reading

- Keele, Luke. 2015. [The Statistics of Causal Inference: A View from Political Methodology](https://dx.doi.org/10.1093/pan/mpv007). *Political Analysis*
- Dunning, Thad. 2010. [Design Based Inference: Beyond the Pitfalls of Regression Analysis](http://www.thaddunning.com/wp-content/uploads/2010/05/Dunning_Rethinking-Social-Inquiry.pdf) in *Rethinking Social Inquiry*
- Sekhon, Jasjeet S. 2009. [Opiates for the Matches: Matching Methods for Causal Inference](http://www.annualreviews.org/doi/abs/10.1146/annurev.polisci.11.060606.135444). *Annual Review of Political Science*
- Grimmer, Justin. 2015. [We're All Social Scientists Now: How Big Data, Machine Learning, and Causal Inference Work Together](http://stanford.edu/~jgrimmer/bd_2.pdf). *PS: Political Science & Politics*
- Angrist, Joshua D., and  Jörn-Steffen Pischke. 2010. [The Credibility Revolution in Empirical Economics: How Better Research Design Is Taking the Con out of Econometrics](https://dx.doi.org/10.1257/jep.24.2.3). *Journal of Economic Perspectives.*
- Gelman, Andrew and Guido Imbens. 2013. [Why ask why? Forward Causal Inference and Reverse Causal Questions](http://www.nber.org/papers/w19614).
- EGAP articles on [10 Strategies for Figuring Out if X Caused Y](http://egap.org/methods-guides/10-strategies-figuring-out-if-x-caused-y) or [10 Things You Need to Know About Causal Inference](http://egap.org/methods-guides/10-things-you-need-know-about-causal-inference).

### <time datetime="2016-04-07">Thursday, April 7</time>

#### Class Agenda

1. Assigned and started working on [Assignment 1](https://github.com/UW-POLS503/Assignment_01)

#### Supplementary Reading

See [Linear Regression Functions in R](regression_in_R.html) for more help

### <time datetime="2016-04-08">Friday, April 8</time>

NO CLASS due to MPSA

[Research Project Assignment 1](assignmens_project_1.html) due at 17:00 PDT.


## Week 3

### <time datetime="2016-04-12">Tuesday, April 12</time>

Class Agenda

- [Conditional Expectation Functions slides](slides/what-is-regression.pdf)
- [Example code](slides/cef_example.R)
- [Conditional Probability: Explained Visually](http://setosa.io/ev/conditional-probability/)
- [Ordinary Least Squares Regression: Explained Visually]http://setosa.io/ev/ordinary-least-squares-regression/

### <time datetime="2016-04-14">Thursday, April 14</time>

**No Class**

- [Assignment 1 due](https://github.com/UW-POLS503/Assignment_01)

### <time datetime="2016-04-15">Friday, April 15</time>

- [Transformations: Logarithm, Squared Terms](lessons_functional_forms2.html)


## Week 4

Topics

- Omitted Variable Bias
- Multiple regression anatomy
- Properties of Ordinary Least Squares
- Inference for Ordinary Least Squares
- Interpretation of p-Values and Confidence Intervals
- Substantive Significance
- Power

Readings

- Wooldridge. *Introductory Econometrics*. Ch 4.
- Wasserstein, Ronald L, and Nicole A. Lazar. 2016. "[The ASA's Statement on p-values: Context, Process, and Purpose](https://dx.doi.org/10.1080/00031305.2016.1154108)". *The American Statistician*.
- Aschwanden. 2015. "[Science Isn't Broken](http://fivethirtyeight.com/features/science-isnt-broken/)" [fivethirtyeight.com](http://fivethirtyeight.com/).
- Gelman, Andrew, and Eric Loken. 2014. "[The Statistical Crisis in Science](http://www.americanscientist.org/issues/pub/2014/6/the-statistical-crisis-in-science/)". *The American Scientist*
- Regina Nuzzo. 2014. [Scientific Method: Statistical Errors](http://www.nature.com/news/scientific-method-statistical-errors-1.14700?WT.mc_id=PIN_NatureNews). *Nature*
- Simply Statistics. 2014. [On the scalability of statistical procedures: why the p-value bashers just don't get it.](http://simplystatistics.org/2014/02/14/on-the-scalability-of-statistical-procedures-why-the-p-value-bashers-just-dont-get-it/)
- Simply Statistics. 2012. [http://simplystatistics.org/2012/01/06/p-values-and-hypothesis-testing-get-a-bad-rap-but-we/](http://simplystatistics.org/2012/01/06/p-values-and-hypothesis-testing-get-a-bad-rap-but-we/)
- Matthew Hankins. 2013. [Still Not Significant](https://mchankins.wordpress.com/2013/04/21/still-not-significant-2/). Online. Probable Error blog.
- xkcd.com. [Significant](https://xkcd.com/882/), [p-values](https://xkcd.com/1478/)

### <time datetime="2016-04-14">Tuesday, April 19</time>

### <time datetime="2016-04-21">Thursday, April 21</time>

### <time datetime="2016-04-22">Friday, April 22</time>


## Week 5

Topics

- Non-constant Variance (Heteroskedasticity)
- Omitted Variable Bias
- Measurement Error
- Multicollinearity
- Outliers
- Non-linearity
- Interaction Terms

Readings

- Wooldrige, Ch. 7: "Multiple Regression Analysis with Qualitative Information"
- Wooldridge, Ch 8: "Heteroskedasticity"
- Wooldridge, Ch 9.1 "Functional Form Misspecification"
- Wooldridge, Ch 9.6 "Least Absolute Deviations Estimation"
- Wooldridge, Ch 9.4 "Properties of OLS under Measurement Error"
- Wooldridge, Ch 17.1: "Logit and Probit Models for Binary Response"
- Brambor, Thomas, and William Roberts Clark, and Matt Golder. 2006.
   "[Understanding Interaction Models: Improving Empirical Analyses](https://dx.doi.org/10.1093/pan/mpi014)" *Political Analysis*
- Matt Golder [Interactions](http://mattgolder.com/interactions)


### <time datetime="2016-04-26">Tuesday, April 26</time>

**Due** Project paper draft #1: Theory, Data Description, and Model Sections.

### <time datetime="2016-04-28">Thursday, April 28</time>

- [slides](sldies/regression-diagnostics.pdf) on overview of OLS assumptions and
    regression diagnostics.

### <time datetime="2016-04-29">Friday, April 29</time>

- [Interactions](https://github.com/UW-POLS503/Assignment_05)


## Week 6


### <time datetime="2016-05-03">Tuesday, May 3</time>

- [slides](slides/diagnostics.pdf) on OVB, Measurement Error, Missing Data, Non-Normal Errors

### <time datetime="2016-05-05">Thursday, May 5</time>

**Due** Peer Review of project draft #1.

### <time datetime="2016-05-06">Friday, May 6</time>


## Week 7

- Model Selection
- Model Fit
- Prediction
- Cross-Validation
- Bootstrapping

Readings

- [Introduction to Statistical Learning](http://www-bcf.usc.edu/~gareth/ISL/). Ch 6.2: "Shrinkage Methods", Ch 5: "Resampling Methods" [pdf](http://www-bcf.usc.edu/~gareth/ISL/ISLR%20Fourth%20Printing.pdf) (skim)

### <time datetime="2016-05-10">Tuesday, May 10</time>

### <time datetime="2016-05-12">Thursday, May 12</time>

### <time datetime="2016-05-13">Friday, May 13</time>

**Due** Project draft analysis


## Week 8

Topics

- Experimental Ideal
- Potential Outcomes
- Selection on Observables: Regression

Readings

- *MHE*, Ch 2: "The Experimental Ideal"
- *MHE*, Ch 3: "Making Regression Make Sense"

### <time datetime="2016-05-17">Tuesday, May 17</time>

### <time datetime="2016-05-19">Thursday, May 19</time>

**Due** Peer review of Project analysis

### <time datetime="2016-05-20">Friday, May 20</time>



## Week 9

- Fixed Effects
- Differences-in-differences
- Clustered Standard Errors

Readings

- *MHE*, Ch 5: "Parallel Worlds"
- *MHE*, Ch 8: "Non-standard Standard Error Issues"
- Wooldridge, Ch 13: "Pooling Cross Sections Across Time"
- Wooldridge, Ch 14: "Advanced Panel Data Methods"

### <time datetime="2016-05-24">Tuesday, May 24</time>

### <time datetime="2016-05-26">Thursday, May 26</time>

### <time datetime="2016-05-27">Friday, May 27</time>

**Due** Peer review of Project analysis



## Week 10

Topics

- Writing, presenting results

Readings

- Wooldrige, Ch 19: "Carrying Out an Empirical Project"
- Schrodt, Philip A. 2014. "[Seven Deadly Sins of Contemporary Quantitative Political Analysis](https://dx.doi.org/10.1177/0022343313499597)." *Journal of Peace Research*

### <time datetime="2016-05-31">Tuesday, May 31</time>

**Due** Draft of project final paper

### <time datetime="2016-06-02">Thursday, June 2</time>

### <time datetime="2016-06-03">Friday, June 3</time>

Poster session

**Due** Peer review of project final paper

## Finals Period

<span id="final-paper-due"><strong>Final paper due on <time datetime="2016-06-08 23:59:00 PDT">June 8, 11:59 pm </time></strong></span>


<!--
- Missing Data
- Weighted Regression
-->
